import 'package:cookie/services/Models.dart';

List<Ingredient> testIngredients = [
  Vegetable('Corn'),
  Vegetable('Green Pepper'),
  Vegetable('Cauliflower'),
  Vegetable('Rucola'),
  Fruit('Oranges'),
  Fruit('Strawberry'),
  Fruit('Banana'),
  Fruit('Mango'),
  Fruit('Peaches'),
  Fruit('Water Melon'),
  Fruit('Blueberry'),
  Fruit('Cherry'),
  Fruit('Apple'),
  Fruit('Kiwi'),
];

List<Ingredient> allIngredients = [
  Vegetable('Green Asparagus'),
  Vegetable('Avocado'),
  Vegetable('Cherry Tomatoes'),
  Vegetable('Broccoli'),
  Vegetable('Eggplant'),
  Vegetable('Cucucumber'),
  Vegetable('Tomatoes'),
  Vegetable('Champinions'),
  Vegetable('Patoto'),
  Vegetable('Zucchini'),
  Vegetable('Carrots'),
  Vegetable('Corn'),
  Vegetable('Green Pepper'),
  Vegetable('Cauliflower'),
  Vegetable('Rucola'),
  Fruit('Oranges'),
  Fruit('Strawberry'),
  Fruit('Banana'),
  Fruit('Mango'),
  Fruit('Peaches'),
  Fruit('Water Melon'),
  Fruit('Blueberry'),
  Fruit('Cherry'),
  Fruit('Apple'),
  Fruit('Kiwi'),
  Fruit('Lime'),
  Fruit('Blackberry'),
  Fruit('Grape'),
  Fruit('Pineapple'),
  Fruit('Lemons'),
  Meat('Pork'),
  Meat('Chicken Breast'),
  Meat('Bacon'),
  Meat('Veal'),
  Meat('Beef'),
  Seafood('Shrimps'),
  Seafood('Salmon'),
  Seafood('Dorade'),
  Seafood('Squid'),
  Seafood('Sea Bream'),
  Seafood('Steckrlfisch'),
  Grain('Rice'),
  Grain('Quinoa'),
  Grain('Couscous'),
  Grain('Mischung'),
  Grain('Arborio Rice'),
  Grain('Jasmine Rice'),
  Grain('wild Rice'),
  Grain('Braun Rice'),
  Pasta('Spaghetti'),
  Pasta('Penne'),
  Pasta('Linguine'),
  Pasta('Strozapretti'),
  Pasta('Taliagtelle'),
  Spice('Salt'),
  Spice('Pepper'),
  Spice('Oregano'),
  Spice('Basil'),
  Spice('Mint'),
  Spice('Tumeric'),
  Spice('Chilli'),
  Spice('Parsley'),
  Spice('Paprika'),
  Spice('Curcuma'),
  Spice('Curry'),
  Spice('Garam Masala'),
  Spice('Coriander'),
  Spice('Sugar'),
  Spice('Vanilla'),
  Spice('Tumeric'),
  Oil('Olive Oil'),
  Oil('Walnut Oil'),
  Oil('Sesamme Oil'),
  Oil('Argan Oil'),
  Oil('Sunflower Oil'),
  Oil('Vegetable Oil'),
  Dairy('Milk'),
  Dairy('Hafer Milk'),
  Dairy('Eggs'),
  Dairy('Butter'),
  Dairy('Cream'),
  Dairy('Yogurt'),
  Dairy('Cheddar'),
  Dairy('Parmigano'),
  Dairy('Mozzarela'),
  Dairy('Brie'),
  Dairy('Blue Cheese'),
  Dairy('Obadza'),
  Dairy('Swiss cheese'),
  Dairy('Brie'),
  Dairy('Coconut Milk'),
  Nut('Pine Nuts'),
  Nut('Peanuts'),
  Nut('Cashews'),
  Nut('Almonds'),
  Nut('Walnuts'),
  Nut('Mixed Nuts'),
  Basic('Garlic'),
  Basic('Onions'),
  Basic('Honey'),
  Basic('Shalloutes'),
  Basic('Ginder'),
  Basic('Veggie Bouillion'),
  Basic('Soy Sauce'),
  Basic('Tariyaki Sauce'),
  Basic('Tomato Sauce'),
  Basic('Worcester Sauce'),
  Basic('BBQ Sauce'),
  Basic('Jam'),
  Basic('Mayo'),
  Basic('Mustard'),
  Basic('Hot Sauce'),
  Basic('Sweet mustard'),
  Basic('Olives'),
  Basic('Coffee'),
  Canned('Tomatoes'),
  Canned('White Beans'),
  Canned('Tuna'),
  Canned('Corn'),
  Canned('Peas'),
  Canned('Kichererbsen'),
  Canned('Ginger'),
  Canned('Ratatoui'),
  Canned('Pickles'),
  Snack('Chips'),
  Snack('Chocolate'),
  Snack('Popcorn'),
  Snack('Fanta'),
  Snack('Candy'),
  Drink('Fanta'),
  Drink('Juice'),
  Drink('Tonic'),
  Drink('Wine white'),
  Drink('Wine red'),
];

List<Ingredient> omeletteIng = [
  Dairy('Eggs'),
  Oil('Sesamme Oil'),
  Oil('Olive Oil'),
  Spice('Salt'),
  Spice('Chilli'),
  Spice('Oregano'),
  Dairy('Kashkaval'),
  Dairy('White Cheese'),
];

List<Ingredient> pastaWithFreshTomatoesIng = [
  Pasta('Linguine'),
  Vegetable('Cherry Tomatoes'),
  Oil('Olive Oil'),
  Spice('Salt'),
  Spice('Sugar'),
  Drink('Radler'),
  Spice('Paprika'),
  Spice('Oregano'),
  Spice('Basil fresh'),
  Dairy('Parmigano'),
  Basic('Garlic')
];

List<Ingredient> saltCrustedDoradeIng = [Seafood('Dorade'), Spice('Salt')];
