import 'package:cookie/services/Models.dart';

List<Ingredient> testIngredients = [
  Vegetable('Corn'),
  Vegetable('Green Pepper'),
  Vegetable('Cauliflower'),
  Vegetable('Rucola'),
  Fruit('Oranges'),
  Fruit('Strawberry'),
  Fruit('Banana'),
  Fruit('Mango'),
  Fruit('Peaches'),
  Fruit('Water Melon'),
  Fruit('Blueberry'),
  Fruit('Cherry'),
  Fruit('Apple'),
  Fruit('Kiwi'),
];

/* List<Ingredient> allIngredients = [
  Vegetable('Green Asparagus'),
  Vegetable('Avocado'),
  Vegetable('Cherry Tomatoes'),
  Vegetable('Broccoli'),
  Vegetable('Eggplant'),
  Vegetable('Cucucumber'),
  Vegetable('Tomatoes'),
  Vegetable('Champinions'),
  Vegetable('Patoto'),
  Vegetable('Zucchini'),
  Vegetable('Carrots'),
  Vegetable('Corn'),
  Vegetable('Green Pepper'),
  Vegetable('Cauliflower'),
  Vegetable('Rucola'),
  Fruit('Oranges'),
  Fruit('Strawberry'),
  Fruit('Banana'),
  Fruit('Mango'),
  Fruit('Peaches'),
  Fruit('Water Melon'),
  Fruit('Blueberry'),
  Fruit('Cherry'),
  Fruit('Apple'),
  Fruit('Kiwi'),
  Fruit('Lime'),
  Fruit('Blackberry'),
  Fruit('Grape'),
  Fruit('Pineapple'),
  Fruit('Lemons'),
  Meat('Pork'),
  Meat('Chicken Breast'),
  Meat('Bacon'),
  Meat('Veal'),
  Meat('Beef'),
  Seafood('Shrimps'),
  Seafood('Salmon'),
  Seafood('Dorade'),
  Seafood('Squid'),
  Seafood('Sea Bream'),
  Seafood('Steckrlfisch'),
  Grain('Rice'),
  Grain('Quinoa'),
  Grain('Couscous'),
  Grain('Mischung'),
  Grain('Arborio Rice'),
  Grain('Jasmine Rice'),
  Grain('wild Rice'),
  Grain('Braun Rice'),
  Pasta('Spaghetti'),
  Pasta('Penne'),
  Pasta('Linguine'),
  Pasta('Strozapretti'),
  Pasta('Taliagtelle'),
  Spice('Salt'),
  Spice('Pepper'),
  Spice('Oregano'),
  Spice('Basil'),
  Spice('Mint'),
  Spice('Tumeric'),
  Spice('Chilli'),
  Spice('Parsley'),
  Spice('Paprika'),
  Spice('Curcuma'),
  Spice('Curry'),
  Spice('Garam Masala'),
  Spice('Coriander'),
  Spice('Sugar'),
  Spice('Vanilla'),
  Spice('Tumeric'),
  Oil('Olive Oil'),
  Oil('Walnut Oil'),
  Oil('Sesamme Oil'),
  Oil('Argan Oil'),
  Oil('Sunflower Oil'),
  Oil('Vegetable Oil'),
  Dairy('Milk'),
  Dairy('Hafer Milk'),
  Dairy('Eggs'),
  Dairy('Butter'),
  Dairy('Cream'),
  Dairy('Yogurt'),
  Dairy('Cheddar'),
  Dairy('Parmigano'),
  Dairy('Mozzarela'),
  Dairy('Brie'),
  Dairy('Blue Cheese'),
  Dairy('Obadza'),
  Dairy('Swiss cheese'),
  Dairy('Brie'),
  Dairy('Coconut Milk'),
  Nut('Pine Nuts'),
  Nut('Peanuts'),
  Nut('Cashews'),
  Nut('Almonds'),
  Nut('Walnuts'),
  Nut('Mixed Nuts'),
  Basic('Garlic'),
  Basic('Onions'),
  Basic('Honey'),
  Basic('Shalloutes'),
  Basic('Ginder'),
  Basic('Veggie Bouillion'),
  Basic('Soy Sauce'),
  Basic('Tariyaki Sauce'),
  Basic('Tomato Sauce'),
  Basic('Worcester Sauce'),
  Basic('BBQ Sauce'),
  Basic('Jam'),
  Basic('Mayo'),
  Basic('Mustard'),
  Basic('Hot Sauce'),
  Basic('Sweet mustard'),
  Basic('Olives'),
  Basic('Coffee'),
  Canned('Tomatoes'),
  Canned('White Beans'),
  Canned('Tuna'),
  Canned('Corn'),
  Canned('Peas'),
  Canned('Kichererbsen'),
  Canned('Ginger'),
  Canned('Ratatoui'),
  Canned('Pickles'),
  Snack('Chips'),
  Snack('Chocolate'),
  Snack('Popcorn'),
  Snack('Fanta'),
  Snack('Candy'),
  Drink('Fanta'),
  Drink('Juice'),
  Drink('Tonic'),
  Drink('Wine white'),
  Drink('Wine red'),
]; */

List<Ingredient> omeletteIng = [
  Dairy('Eggs'),
  Oil('Sesamme Oil'),
  Oil('Olive Oil'),
  Spice('Salt'),
  Spice('Chilli'),
  Spice('Oregano'),
  Dairy('Kashkaval'),
  Dairy('White Cheese'),
];

List<Ingredient> pastaWithFreshTomatoesIng = [
  Pasta('Linguine'),
  Vegetable('Cherry Tomatoes'),
  Oil('Olive Oil'),
  Spice('Salt'),
  Spice('Sugar'),
  Drink('Radler'),
  Spice('Paprika'),
  Spice('Oregano'),
  Spice('Basil fresh'),
  Dairy('Parmigano'),
  Basic('Garlic')
];

List<Ingredient> saltCrustedDoradeIng = [Seafood('Dorade'), Spice('Salt')];

Ingredient dorade = Ingredient(
    category: 'fisch',
    isEmpty: false,
    name: 'Dorade',
    measurement: 'g',
    quantity: '600g');
Ingredient salt = Ingredient(
    category: 'basic',
    isEmpty: false,
    name: 'Salz',
    measurement: 'g',
    quantity: '1kg');
List<Ingredient> testIng = [dorade, salt];

Steps one = Steps(orderId: 1, action: 'preheat oven');
Steps two = Steps(orderId: 2, action: 'pour salt over fish');
Steps three = Steps(orderId: 3, action: 'bake for 45 min');

List<Steps> testSteps = [one, two, three];

const gemuese = [
  'Blumenkohl',
  'Brokkoli',
  'Chinakohl',
  'Grünkohl',
  'Pok Choi'
      'Romanesco',
  'Rosenkohl',
  'Rotkohl',
  'Spitzkohl',
  'Weißkohl',
  'Bratpaprika',
  'Garten-Salat',
  'Rucola',
  'Eisbergsalat',
  'Feldsalat',
  'Kopfsalat',
  'Schnittsalat',
  'Bärlauch',
  'Brennessel'
      'Mangold',
  'Kapern',
  'Zucchini',
  'Fenchel',
  'Frühlingslauch',
  'Kartoffel',
  'Kohlrabi',
  'Lauch',
  'Radieschen',
  'Rettich',
  'Salatgurke',
  'Sellerie',
  'Weiße Spargel',
  'Grüne Spargel',
  'Staudensellerie',
  'Zuckerschoten',
  'Tomaten',
  'Cherry Tomaten',
  'Zuckermais',
  'Auberginen',
  'Artischocken',
  'Bohnen',
  'Gemüsezwiebeln',
  'Paprika',
  'Kürbis',
  'Oliven',
  'Rote Bete',
];

const obst = [
  'Ananas'
      'Avocado'
      'Banane',
  'Guave',
  'Kaktusfeige',
  'Kapstachelbeere',
  'Kiwi',
  'Kokosnuß',
  'Mango',
  'Melone',
  'Papaya',
  'Maracuja',
  'Tafeltrauben',
  'Zitrone',
  'Kumquat',
  'Limette',
  'Orange',
  'Birne',
  'Kirschen',
  'Grapefruit',
  'Wassermelone',
  'Aprikose',
  'Brombeeren',
  'Himbeeren',
  'Johannisbeeren',
  'Pfirsich',
  'Zwetschge',
  'Sauerkirschen',
  'Süßkirschen',
  'Frühapfel',
  'Heidelbeeren',
  'Quitte',
  'Weintraube',
  'Walderdbeeren',
  'Grapefruit',
  'Mirabelle',
  'Nektarine',
  'Wassermelone',
  'Datteln',
  'Granatapfel',
  'Karambole',
  'Kaktusfeige',
  'Äpfel',
  'Cherimoya',
  'Cranberry',
  'Feigen',
  'Granatapfel',
  'Hagebutte',
  'Holunder',
  'Kaktusfeige',
  'Nashi',
  'Preiselbeere',
  'Schlehe',
  'Tamarillo',
  'Mandarine',
  'Kaki',
  'Erdbeere',
  'Pflaume',
  'Stachelbeere',
  'Pitahaya',
];

const kreuter = [
  'Basilikum',
  'Bohnenkraut',
  'Dill',
  'Estragon',
  'Kerbel',
  'Koriander',
  'Lorbeer',
  'Majoran',
  'Minze',
  'Oregano',
  'Petersilie',
  'Rosmarin',
  'Salbei',
  'Schnittlauch',
  'Thymian',
  'Zitronenmelisse',
];

const gewuerze = [
  'Anis',
  'Chili',
  'Curry',
  'Zucker',
  'Kurkuma',
  'Ingwer',
  'Sternanis',
  'Kardamom',
  'Kümmel',
  'Pfeffer',
  'Pfeffer weiß',
  'Pfeffer rot',
  'Pfeffer rosa',
  'Muskatnuß',
  'Nelken',
  'Paprika',
  'Piment',
  'Safran',
  'Senfkörner',
  'Vanille',
  'Salz',
  'Cayennepfeffer',
  'Estragon',
  'Zitronengrass',
  'Sesam',
  'Wasabi',
  'Garam Masala',
  'Miso',
  'Soya-Sauce',
  'Hoisin-Sauce',
  'Fischsauce',
  'Essig',
  'Fischsauce',
  'Mango-Essig',
  'Apfel-Essig',
  'Reis-Essig',
  'Fischsauce',
  'Zimt',
];

const nuesse = [
  'Cashewkerne',
  'Colanuss',
  'Paranüsse',
  'Pekannuss',
  'Pinienkerne',
  'Pistazien',
  'Walnüsse',
  'Erdnüsse',
  'Mandeln',
  'Haselnüsse',
  'Macadamianüsse',
  'Maroni',
];

const huelse = [
  'Augenbohnen',
  'Kichererbse',
  'Linsen',
  'Mungbohne',
  'Saubohne',
  'Schwarze Bohne',
  'Sojabohne',
  'Straucherbse',
  'Urdbohne',
  'Borlottibohne',
  'Kaiserschotten',
  'Edamame',
  'Arborio Reis',
  'Jasmine Reis',
  'Wild Reis',
  'Braun Reis',
];

const fette = [
  'Olivenöl',
  'Palmöl',
  'Pflanzenöl',
  'Sonnenblumenöl',
  'Rapsöl',
  'Kokusnussöl',
  'Arganöl',
  'Wallnussöl',
  'Sesamöl',
  'Chilliöl',
  'Kokosmilch',
];

const fleisch = [
  'Kaninchen',
  'Hirsch',
  'Huhn',
  'Hühnerbrust',
  'Hühnerschenkel',
  'Kalb',
  'Krokodil',
  'Lamm',
  'Perlhuhn',
  'Rind',
  'Schwein',
  'Wildschwein',
];

const fisch = [
  'Seeteufel',
  'Makrele',
  'Goldbrasse',
  'Barrakuda',
  'Schnapper',
  'Sichelfisch',
  'Thunfisch',
  'Stachhelmakrele',
  'Wolfsbarsch',
  'Seehecht',
  'Hering',
  'Sardelle',
  'Sardine',
  'Aal',
  'Dorade',
  'Forelle',
  'Saibling',
  'Heilbutt',
  'Kabeljau',
  'Karpfen',
  'Lachs',
  'Pangasius',
  'Scholle',
  'Seezunge',
  'Zander',
];

const meeresfruechte = [
  'Austern',
  'Frosch',
  'Garnelen',
  'Kalmare',
  'Kammmuscheln',
  'Krabben',
  'Krake',
  'Miesmuscheln',
  'Muschel vom Lac Flouz',
  'Schildkröte',
  'Seeigel',
  'Sepia',
  'Venusmuscheln',
  'Wasserkäfer',
];

const getreide = [
  'Weizen',
  'Dinkel',
  'Rogggen',
  'Gerste',
  'Hafer',
  'Hirse',
  'Linsen',
  'Rote Linsen',
  'Hirse',
  'Buchweizen',
  'Amaranth',
  'Quinoa',
  'Chia',
  'Emmer',
  'Einkorn',
];
const pilze = [
  'Steinpilze',
  'Pfifferling',
  'Champignon',
  'Shiitake-Pilz',
  'Austernpilz',
  'Herbsttrompete',
  'Morchel',
];
const milchprodukte = [
  'Crème fraîche',
  'Butter',
  'Milch',
  'Buttermilch',
  'Joghurt',
  'Kefir',
  'Saure Sahne',
  'Schmand',
  'Fruchtjoghurt',
  'Schlagsahne',
  'Butterschmalz',
  'Milchpulver',
  'Quark',
];
const kaese = [
  'Schafskäse',
  'Ziegenkäse',
  'Appenzeller',
  'Emmentaler',
  'Greyerzer',
  'Cheddar',
  'Comté',
  'Jurassic',
  'Sbrinz',
  'Bergkäse',
  'Chester',
  'Parmesan',
  'Grana Padano',
  'Pecorino',
  'Butterkäse',
  'Edamer',
  'Gouda',
  'Kaschkawal',
  'Leerdammer',
  'Morbier',
  'Steppenkäse',
  'Subenhara',
  'Tilsiter',
  'Raclette Schnittkäse',
  'Bavaria blu',
  'Danablu',
  'Roquefort',
  'Gorgonzola',
  'Cabrales',
  'Mozzarella',
  'Hüttenkäse',
  'Brie ',
  'Camembert ',
  'Géramont ',
  'Chaumes ',
  'Bresso Weichkäse',
  'Feta',
  'Ricotta',
  'Halloumi',
  'Manuri',
];
const basics = [
  'Knoblauch',
  'Zwiebeln',
  'Salz',
  'Zucker',
  'Schalotte',
  'Honig',
  'Bouillion',
  'Tariyaki Sauce',
  'Worcester Sauce',
  'Soya Soße',
  'Tomatensoße',
  'Mayo',
  'Senf',
  'Senf süß',
  'Oliven',
  'Kaffee',
  'Ingwer',
  'Wasser',
  'Wein weiß',
  'Wein rot',
  'Chips',
  'Shokolade',
];
const pasta = [
  'Spaghetti',
  'Penne',
  'Linguine',
  'Lasagne',
  'Fettucine',
  'Tagliolini',
  'Ravioli',
  'Paccheri',
  'Orzo',
  'Fusilli',
  'Farfalle',
  'Gnocchi',
  'Tagliatelle',
  'Strozzapreti',
  'Trodie',
  'Spätzle',
  'Makkaroni',
  'Pappardelle',
];
